### ISSUE TITLE
iOS Smart Banner

### ISSUE THREAD

**Issue by jeremywight** [codeforgreenville/trolley-tracker-web#12]
@dacohenii Here are the details for integrating the iOS web app banner https://developer.apple.com/library/content/documentation/AppleApplications/Reference/SafariWebContent/PromotingAppswithAppBanners/PromotingAppswithAppBanners.html

**Comment by allella** [comment]
@dacohenii I think this is [recent Chrome info](https://developers.google.com/web/fundamentals/engage-and-retain/app-install-banners/).

**Comment by jeremywight** [comment]
Yeah I read the whole post this time and I see at the bottom where it lists
how to serve the  Native App Banner.


Still requires HTTPS, So we'd need to decide if we want to pay for an
annual cert to add that functionality ~$125/yr

**Comment by jeremywight** [comment]
I added the iOS links and tested for www.yeahthattrolley.com and
www.trackthetrolley.com. So those are now working, just need to decide on
Android.

**Comment by bikeoid** [comment]
Re: HTTPS - LetsEncrypt is free and widely used

**Comment by ajhodges** [comment]
+1 to letsencrypt

**Comment by jeremywight** [comment]
Awesome!

**Comment by allella** [comment]
Yes, Let's Encypt is free and cheap but plenty sufficient certificates are $9/year via Namecheap.

**Comment by allella** [comment]
@jeremywight we were talking again about the need for an SSL certificate on http://www.trackthetrolley.com but also brought up we've been planning to use yeahthattrolley.com for the street pole sign and A-frame.

That being the case we should probably have SSL on both domains since it's possible someone types in  https://  yeahthattrolley.com and gets no response. Modern browsers require a valid SSL on the redirecting domain as well.

What's the thought on making yeahthattrolley.com the primary domain and redirecting www.trackthetrolley.com?

Also, do you control the DNS for both domains?

**Comment by jeremywight** [comment]
Hmm, yes I do, but I can't apply SSL cert to yeaththattrolley.com because
it's merely a redirect, versus an actual hosted domain. I assumed since
it's a redirect that it would be covered, but I guess not?

**Comment by dacohenii** [comment]
I set up the smart banner for android -- turns out SSL is not needed. 

@jeremywight - can we update `yeahthattrolley.com` to forward to `trackthetrolley.com` instead of `/greenville-sc-trolley`? (I only updated the former)

**Comment by allella** [comment]
If SSL becomes necessary then we could point the domain's A records to a real web server and have the web server do the 301 redirect.  I'm assuming the current redirect is done in the DNS.

**Comment by dacohenii** [comment]
Looks like we're good. Live and stable.
