### ISSUE TITLE
Trolley's offline content

### ISSUE THREAD

**Issue by agautsc** [codeforgreenville/trolley-tracker-web#2]
Linking to a PDF scares me. How about we just drop the schedule in message.

<ul>
<li><strong>Thursday:</strong> 6:00 p.m. - 11:00 p.m. </li>
<li><strong>Friday Lunch:</strong> 11:00 a,m.- 2:00 p.m.</li>
<li><strong>Friday:</strong> 6:00 p.m. - 11:00 p.m. </li>
<li><strong>Saturday:</strong> 10:00 a.m. - 11:00 p.m. </li>
<li><strong>Sunday:</strong> 1:00 p.m. - 8:00 p.m.</li>
</ul>

**Comment by ajhodges** [comment]
Personally I was just going to consume and display http://api.yeahthattrolley.com/api/v1/RouteSchedules assuming that data is accurate

**Comment by agautsc** [comment]
:+1: to Hodges idea.

**Comment by bikeoid** [comment]
I agree that this is best.   I haven't quite come to terms with the best way to handle route variations - for example, would there be a separate route for the Saturday Market time slot?  Or, somehow define this as a variation?   So there may be several route variations during the day, and possibly just list the current or next active day to minimize the list of items to show.

**Comment by jeremywight** [comment]
Agreed with Hodges... Mike, when I rode it was during Sat morning market
time,, they did vary the route, though it's not an "official" route. That's
why I was thinking if there was a way for us to record the route taken and
if that same route is run more than 3 times, then dynamically set that as
the current route, rather than relying on their predefined schedule which
will likely always have some issues.

**Comment by Linktheoriginal** [comment]
Not pushed to production yet, but updated for colors and to consume the data from the API instead of linking.  Want to test the new changes on working data before I push.  The issue I see with consuming the api data for the schedule is that there's no name associated in the schedule summary data - all I can display is the schedule/route ID.  Can we attach user-friendly names to these in the call?
![image](https://cloud.githubusercontent.com/assets/574842/9893373/e9160758-5be5-11e5-92b6-8e2558664c64.png)

**Comment by bikeoid** [comment]
The Routes API call at http://api.yeahthattrolley.com/api/v1/Routes will return the ShortName, LongName and Description for these route numbers.    I'm guessing that LongName will be the most useful on this page.     I'll probably need to go through and make those names consistent and make sense to a visitor.      It should also be sorted server side to be more readable.

**Comment by bikeoid** [comment]
> if that same route is run more than 3 times, then dynamically set that as
the current route

  I like the idea of dynamic routes because they would also automatically handle things like all the detours for closed streets in the last few weeks as well as the festival closures.    When they change dynamically, 3 passes will take some time to re-validate - approximately 45-60 minutes.   I think changing for 2 is not enough.  Saturday Market might be repeatable enough to make that a separate schedule.     

There are some odd things, such as the ballpark route going around to the ticket office only if someone asks for that dropoff point.   So we wouldn't want to dynamically change the route if the most frequent case is the short direct shuttle between University Square and the ballpark, but there might have been 3 'ticket office' riders in a row.

**Comment by Linktheoriginal** [comment]
Can we add that field to the summary call so I don't have to make extra api calls for each route?  I'll handle sorting by day/time to make the order friendlier.

**Comment by bikeoid** [comment]
The API call in the link above returns all trolleys at once.   But it would be one separate call in addition to checking the schedule - is it still worth adding to the schedule data?

**Comment by Linktheoriginal** [comment]
Added the additional call to the server-side, along with ordering by day.  It would save me some overhead by making it a single call in the future.

**Comment by bikeoid** [comment]
This will be in the next publish cycle.
